on:
  push:
    branches:
      - main
    tags:
      - 'release-v*'
env:
  MVN_ARGS: -ntp -B -V -Pci-log -Pwarn-log -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.shade=warn -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.dependency=warn
  MODULES: "hudi-sync/hudi-datahub-sync,hudi-sync/hudi-hive-sync,hudi-sync/hudi-sync-common,hudi-utilities,hudi-aws,hudi-gcp,hudi-examples/hudi-examples-spark"
  AWS: "aws"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - scalaProfile: "scala-2.12"
            sparkProfile: "spark3.2"
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::194159489498:role/GithubActionsPublishHudi-RepositoryPublisherRole-10H7ABJVFNSQ9
          role-session-name: HudiPublishSession
          role-duration-seconds: 900
      - name: Set Env
        run: echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain onehouse --domain-owner 194159489498 --query authorizationToken --output text)" >> $GITHUB_ENV
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          server-id: codeartifact
          server-username: AWS
          server-password: CODEARTIFACT_AUTH_TOKEN
      - name: Set COMMIT_HASH
        run: echo "COMMIT_HASH=$(git rev-parse $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Set TAG_PRESENT_IN_COMMIT
        run: echo "TAG_PRESENT_IN_COMMIT=$(git tag --contains $COMMIT_HASH | head -1 | sed -e s/release-//)" >> $GITHUB_ENV
      - name: Set java version
        if: env.TAG_PRESENT_IN_COMMIT != ''
        run: mvn versions:set -DnewVersion=$TAG_PRESENT_IN_COMMIT -T 4 -D"$SCALA_PROFILE" -D"$SPARK_PROFILE" $MVN_ARGS
      - name: Deploy
        if: env.TAG_PRESENT_IN_COMMIT != ''
        run: mvn deploy -am -pl packaging/hudi-utilities-bundle,packaging/hudi-utilities-slim-bundle,hudi-aws,packaging/hudi-spark-bundle -DskipTests -T 4 -D"$SCALA_PROFILE" -D"$SPARK_PROFILE" $MVN_ARGS